exclude: |
  (?x)(
    ^testcases/testcase1/models/wrapped.mo|
    ^testcases/testcase2/models/wrapped.mo|
    ^testcases/testcase3/models/wrapped.mo
  )

repos:
  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
        args: ['--maxkb=50000']
      - id: mixed-line-ending
      - id: end-of-file-fixer
      - id: check-merge-conflict
#      - id: check-ast
#      - id: check-json
#      - id: check-xml
#      - id: check-yaml
#      - id: debug-statements
#      - id: flake8
#        args: ['--max-line-length=140']  # default of Black
#      - id: pretty-format-json
#        args: ['--autofix', '--no-sort-keys']
#  - repo: https://github.com/pre-commit/mirrors-autopep8
#      rev: ''
#      hooks:
#        - id: autopep8
#  - repo: https://github.com/pre-commit/mirrors-isort
#    rev: v4.3.4
#    hooks:
#      - id: isort
#        args: ['-m 3']  # vertical hanging
#  - repo: local
#    hooks:
#      - id: modelica-fmt
#        name: Modelica Formatter
#        types: [file]
#        files: \.(mo)$
#        entry: modelicafmt
#        args: ["-w"]
#        language: system
